### ISSUE TITLE
Process Family Design Project and Costing Plugin

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#1113]
# Description
Testing the Process Family Design Project and Costing Plugin.  

## TODOs
- [ ] Copy and Paste Results from Node Edit ( below )
- [ ] Investigate `foqus_lib\framework\sampleResults\results.py:375: PerformanceWarning: DataFrame is highly fragmented.`
- [ ] Research how IPOPT installed differently for FOQUS and IDAES

# Steps
 
Navigate to your desired installation location for IDAES in your Anaconda shell and follow the installation instructions for idaes-pse.

- If IDAES is not installed, first run `pip install idaes-pse` for a user installation and `pip install -r requirements-dev-txt` for a Git installation.
  - If you have a current installation, run `pip install -U idaes-pse` and then `pip install -U .` to update IDAES and all dependencies.
  - You should have idaes-pse version 2.0.0.0dev3 and pyomo version 6.4.5a0.
Here are the official docs: https://idaes-pse.readthedocs.io/en/latest/tutorials/getting_started/index.html
 
- Navigate to your desired installation location for FOQUS and repeat step 1 for ccsi-foqus.
  - You should have ccsi-foqus version 3.17.dev0 and TurbineClient version 4.0.2.
  - You may need to install PSUADE, SimSinter and Turbine separately per the official docs: 
 https://foqus.readthedocs.io/en/stable/chapt_install/index.html
 
- Copy the file `CCS_costing_plugin.py` into your `FOQUS-wd/user_plugin/` folder. This will let FOQUS find the plugin.
 
- Launch FOQUS and make sure the plugin is loaded. If you see a message about a missing dependency, check that IDAES and Pyomo are correctly installed.
  - One or more other plugins such as SM OPT or the MEA Column Model neural network models may not load. This is fine if the CCS Costing Plugin loads correctly.
 
- Open one of Miguel sessions and Update Turbine with the corresponding JSON file.
  - Go to the Aspen node and clear/re-select the Turbine model, and test running the two nodes individually from the Node Editor and then the entire flowsheet. 
    - The Aspen node should run in 5-10 minutes or less, and the Python node should run quickly.
  - Separate Aspen and json files are used for ‘HighConcentration’ and ‘LowConcentration’ for baselines of 14% and 5% CO2 in flue gas, respectively. The four FOQUS files are as follows:
    - LowConcentration.foqus – uses the Aspen file with default of 5% CO2 in flue gas and contains the UQ ensemble with 1440 runs for 5 and 8% CO2
    - LowConcentration_FullSample – uses the Aspen file with default of 5% CO2 in flue gas and contains the UQ ensemble with all 2880 runs
    - HighConcentration.foqus – uses the Aspen file with default of 14% CO2 in flue gas and contains the UQ ensemble with 1440 runs for 11 and 14% CO2
    - HighConcentration_FullSample – uses the Aspen file with default of 14% CO2 in flue gas and contains the UQ ensemble with all 2880 runs
  - First try the LowConcentration_FullSample.foqus foqus session.
    - The session is ready to run, you simply need to open the session, load Aspen file (LowConcentration) and dlls (ccsi.opt and ccsi11.dll) to turbine.
    - Then go to UQ Ensemble and run samples (we already loaded the samples for you).

**Comment by boverhof** [comment]
# Aspen12 VM
## IDAES GIT versions
```
(foqus) C:\Users\Administrator\Desktop\idaes-pse>idaes --version
idaes, version 2.0.0.dev3

(foqus) C:\Users\Administrator\Desktop\idaes-pse>pyomo  --version
Pyomo 6.5.0 (CPython 3.8.13 on Windows 10)
```

**Comment by lbianchi-lbl** [comment]
@boverhof Are the IDAES solvers installed? https://idaes-pse.readthedocs.io/en/2.0.0b2/tutorials/getting_started/windows.html#install-idaes-extensions

**Comment by bpaul4** [comment]
@boverhof have you tested directly installing the IDAES extensions, as suggested above? Please let me know if you encounter further obstacles setting up the environment or Python packages.

**Comment by boverhof** [comment]
# IPOPT Solver Available
- Wonder how idaes and FOQUS have different plugin or 'extension' structure and maybe we can leverage what they've done.
```
(foqus) C:\Users\Administrator\Desktop>idaes get-extensions
Getting files...
Done
---------------------------------------------------
IDAES Extensions Build Versions
===================================================
Solvers:  v3.2.0 20230203-1520 windows-x86_64
Library:  v3.2.0 20230203-1552 windows-x86_64
===================================================

(foqus) C:\Users\Administrator\Desktop>ipopt
'ipopt' is not recognized as an internal or external command,
operable program or batch file.

(foqus) C:\Users\Administrator\Desktop>python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from idaes.core.solvers import get_solver
>>> solver = get_solver()
>>> solver.available()
True
>>> solver
<pyomo.solvers.plugins.solvers.IPOPT.IPOPT object at 0x0000018581851790>
>>>
```

**Comment by boverhof** [comment]
# PerformanceWarning: DataFrame is highly fragmented
- Loading `LowConcentration.foqus`
```
C:\ProgramData\Anaconda3\envs\foqus\lib\site-packages\foqus_lib\framework\sampleResults\results.py:375: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  self[c] = []
```

**Comment by boverhof** [comment]
# LowConcentration Flowsheet Runs on OVIRT/VM Aspen12
<img width="674" alt="Screen Shot 2023-03-06 at 8 03 33 AM" src="https://user-images.githubusercontent.com/738295/223170986-f3235d14-40bf-4b99-8cbc-7cd6bb378f76.png">

**Comment by bpaul4** [comment]
@boverhof great! I'm glad the file is working as expected. When you have a moment, could you please share the file and results with me? Thank you!

**Comment by boverhof** [comment]
# LowConcentration_FullSample
- Aspen12 VM ( non-cloud )
- Runs but after a couple hours stopped it

<img width="1439" alt="Screen Shot 2023-03-06 at 11 01 15 AM" src="https://user-images.githubusercontent.com/738295/223206340-16058025-1e14-47fa-aad2-f4477fd81a96.png">

**Comment by boverhof** [comment]
# HighConcentration Success
<img width="1267" alt="Screen Shot 2023-03-06 at 11 34 50 AM" src="https://user-images.githubusercontent.com/738295/223212490-adc670e6-bf27-4a92-9bcc-36bf97614cd1.png">

**Comment by boverhof** [comment]
# AWS VM
- configure idaes 
```
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\81\03\84\acbaef8b5bc2ecc1bf944c572037d0fb232a19b19a96579f97
Successfully built bunch
Installing collected packages: webencodings, wcwidth, Send2Trash, ply, pickleshare, mpmath, mistune, ipython-genutils, fastjsonschema, bunch, backports.shutil-get-terminal-size, backcall, xlrd, widgetsnbextension, Werkzeug, webcolors, uri-template, traitlets, tornado, tinydb, tinycss2, sympy, soupsieve, sniffio, rfc3986-validator, rfc3339-validator, pyzmq, pywinpty, python-json-logger, pyrsistent, pyomo, pycparser, prompt-toolkit, prometheus-client, pkgutil-resolve-name, pint, parso, pandocfilters, nest-asyncio, lxml, jupyterlab-widgets, jupyterlab-pygments, jsonpointer, itsdangerous, importlib-resources, fqdn, et-xmlfile, distro, defusedxml, decorator, debugpy, bleach, terminado, rbfopt, qtpy, pandas, openpyxl, omlt, matplotlib-inline, jupyter-core, jsonschema, jedi, flask, comm, cffi, beautifulsoup4, arrow, anyio, nbformat, jupyter-server-terminals, jupyter-client, isoduration, ipython, flask-cors, argon2-cffi-bindings, nbclient, ipykernel, argon2-cffi, qtconsole, nbconvert, jupyter-events, jupyter-console, ipywidgets, jupyter-server, notebook-shim, nbclassic, notebook, jupyter, idaes-pse
  Attempting uninstall: pandas
    Found existing installation: pandas 1.5.0
    Uninstalling pandas-1.5.0:
      Successfully uninstalled pandas-1.5.0
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\tools\\Anaconda3\\envs\\foqus\\Lib\\site-packages\\~andas\\_libs\\algos.cp38-win_amd64.pyd'
Consider using the `--user` option or check the permissions.
```

**Comment by boverhof** [comment]
# Two TurbineApp nodes Error
- flowsheet that is sent to Cloud has CCS_Costing labeled as a AspenPlus simulation
- 
```
(foqus) C:\ProgramData\foqus_service>python
Python 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from foqus_lib.service.flowsheet import getfilenames
>>> sfile, rfile, vfile, ofile = getfilenames('ad2e71fe-b268-4d93-8ab8-2500f399fcb4')
>>> sfile
'C:\\ProgramData\\foqus_service\\ad2e71fe-b268-4d93-8ab8-2500f399fcb4\\session.foqus'
>>> sd = json.load(open(sfile))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'json' is not defined
>>> import json
>>> sd = json.load(open(sfile))
>>> sd['flowsheet']['nodes']['CCS_costing']
{'modelType': 1, 'modelName': 'CCS_costing_plugin', 'x': 0.0, 'y': -100.0, 'z': 0.0, 'scriptMode': 'post', 'pythonCode': '', 'calcError': -1, 'options': {'order': [], 'options': {}}, 'turbApp': ['AspenPlus', 'aspenfile'], 'turbSession': None, 'synced': True}
>>>
```

**Comment by boverhof** [comment]
# Change Flowsheet CCS_costing_plugin 
- turbApp : None

```
>>> import json
>>> sd = json.load(open('C:\Users\Administrator\Downloads\Prepare for AWS\Prepare for AWS\LowConcentration.foqus'))
  File "<stdin>", line 1
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
>>>
>>> sd = json.load(open('C:\\Users\\Administrator\\Downloads\\Prepare for AWS\\Prepare for AWS\\LowConcentration.foqus'))
>>> sd.keys()
dict_keys(['CCSIFileMetaData', 'Type', 'ID', 'flowsheet', 'optProblem', 'surrogateProblem', 'surrogateCurrent', 'uqSimList', 'uqFilterResultsList', 'sdoeSimList', 'sdoeFilterResultsList', 'odoeCandList', 'odoeEvalList'])
>>> sd['flowsheet']['nodes']['CCS_costing']
{'modelType': 1, 'modelName': 'CCS_costing_plugin', 'x': 0.0, 'y': -100.0, 'z': 0.0, 'scriptMode': 'post', 'pythonCode': '', 'calcError': -1, 'options': {'order': [], 'options': {}}, 'turbApp': ['AspenPlus', 'aspenfile'], 'turbSession': None, 'synced': True}
>>> sd['flowsheet']['nodes']['CCS_costing']['turbApp'] = None
>>> fd = open('C:\\Users\\Administrator\\Downloads\\Prepare for AWS\\Prepare for AWS\\LowConcentration.foqus', 'w')
>>> json.dump(sd, fd)
>>> fd.close()
>>> sd = json.load(open('C:\\Users\\Administrator\\Downloads\\Prepare for AWS\\Prepare for AWS\\LowConcentration.foqus'))
>>> sd['flowsheet']['nodes']['CCS_costing']
{'modelType': 1, 'modelName': 'CCS_costing_plugin', 'x': 0.0, 'y': -100.0, 'z': 0.0, 'scriptMode': 'post', 'pythonCode': '', 'calcError': -1, 'options': {'order': [], 'options': {}}, 'turbApp': None, 'turbSession': None, 'synced': True}
>>> quit()
```

**Comment by boverhof** [comment]
# Missing Plugin on FOQUS Cloud Worker
- need to figure out a way to provide the plugin

```
2023-03-08 01:48:23,811 - DEBUG - foqus.foqus_lib.framework.graph.graph - Turbine Result Generator Results LEN: 1
2023-03-08 01:48:23,811 - ERROR - foqus.foqus_lib.framework.graph.graph - Job(32792c39-0d2b-41af-acda-461fffbd361b) Error: Flowsheet Error: ['Traceback (most recent call last):\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\graph.py", line 873, in run\n    self.solve()\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\graph.py", line 1034, in solve\n    self.runGraph(order)\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\graph.py", line 1345, in runGraph\n    elif self.runNode(name) != 0:\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\graph.py", line 1357, in runNode\n    node.runCalc()\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\node.py", line 1303, in runCalc\n    self.runModel()\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\node.py", line 1324, in runModel\n    self.runPymodelPlugin()\n', '  File "c:\\users\\administrator\\desktop\\foqus\\foqus_lib\\framework\\graph\\node.py", line 1365, in runPymodelPlugin\n    self.pyModel = self.gr.pymodels.plugins[self.modelName].pymodel_pg()\n', "KeyError: 'CCS_costing_plugin'\n"]
2023-03-08 01:48:24,249 - DEBUG - foqus.foqus_lib.gui.main.mainWindow - stopSim SingleRun: {'solTime': 0, 'input': {'graph': {}, 'CCSI_MEAModel': {'ABSDIAM': 1, 'ABSPACKHT': 30, 'STRDIAM': 1, 'STRPACKHT': 25, 'CO2LEANLOADING': 0.2, 'LEANRICHHXAREASPEC': 80, 'LEANSOLVENTTEMP': 40, 'FLUEGASINTEMP': 40, 'STRPRESSURE': 185, 'FLUEGASINFLOW': 2000, 'FLUEGASFRACCO2': 0.05, 'FLUEGASFRACO2': 0.084, 'FLUEGASFRACH2O': 0.086, 'FLUEGASFRACN2': 0.78}, 'CCS_costing': {'Absorber.Volume': 22.5538944, 'Absorber.Packing_Volume': 22.1028165, 'Stripper.Volume': 3.22889153, 'Stripper.Packing_Volume': 3.1643137, 'Condenser.Area': 0.936174117, 'Stripper.Reboiler_Area': 1.35659952, 'LeanRichHX.Area': 52.034442, 'LeanSolventCooler.Area': 1.13815527, 'CO2Product.Flow': 1152.69703, 'FlueGas.Flow': 2002.0657, 'NetPlantPower': 650, 'Utilities.Water': 86.623102, 'Utilities.Steam': 879.971152, 'Utilities.Solvent': 1.75976342, 'Utilities.Electricity': 72.7716987, 'CE_Index.Year': 2018}}, 'output': {'graph': {'error': -1}, 'CCSI_MEAModel': {'ABSVOLUME': 0, 'ABSPACKVOL': 0, 'STRVOLUME': 0, 'STRPACKVOL': 0, 'CONDENSERAREA': 0, 'STRREBAREA': 0, 'LEANRICHHXAREA': 0, 'COOLERAREA': 0, 'CO2PRODFLOW': 0, 'FLUEGASFLOW': 0, 'RATEWATER': 0, 'RATESTEAM': 0, 'RATEMEA': 0, 'RATEELECTRICITY': 0, 'CO2FRACCAP': 0, 'ABSFRACFLOOD': 0, 'STRFRACFLOOD': 0, 'LEANSOLVFLOW': 5796.48792, 'QREB': 347712.253, 'SRD': 3.35810066, 'status': 0}, 'CCS_costing': {'Absorber.Total_Plant_Cost': 1.3886593705269759, 'Absorber.Packing.Total_Plant_Cost': 1.203395894325608, 'Stripper.Total_Plant_Cost': 0.20634864588003515, 'Stripper.Packing.Total_Plant_Cost': 0.15770819055219565, 'Stripper.Condenser.Total_Plant_Cost': 0.00894523073157076, 'Stripper.Reboiler.Total_Plant_Cost': 0.042815990775907316, 'LeanRichHX.Total_Plant_Cost': 0.11411726654844366, 'LeanSolventCooler.Total_Plant_Cost': 0.031603827573924874, 'FlueGasBlower1.Total_Plant_Cost': 0, 'FlueGasBlower2.Total_Plant_Cost': 0.016680830876214244, 'FlueGasDirectContactCooler1.Total_Plant_Cost': 0.05906082360728565, 'FlueGasDirectContactCooler2.Total_Plant_Cost': 0, 'FlueGasDirectContactCooler1.Packing.Total_Plant_Cost': 0.07328818635677407, 'FlueGasDirectContactCooler2.Packing.Total_Plant_Cost': 0.03868227160087614, 'PretreatmentPump1.Total_Plant_Cost': 0.007862035923562593, 'PretreatmentPump2.Total_Plant_Cost': 0, 'PretreatmentCooler1.Total_Plant_Cost': 0, 'PretreatmentCooler2.Total_Plant_Cost': 0.004149664823885809, 'PretreatmentTank1.Total_Plant_Cost': 0.0036196502024322826, 'PretreatmentTank2.Total_Plant_Cost': 0.001910489250600892, 'WashingColumn1.Total_Plant_Cost': 0.11061339650873707, 'WashingColumn2.Total_Plant_Cost': 0.05838290806674986, 'WashingColumn1.Packing.Total_Plant_Cost': 0.080177198032371, 'WashingColumn2 .Packing.Total_Plant_Cost': 0.04231836404556815, 'WashingColumn1.Cooler.Total_Plant_Cost': 0.002685546924385242, 'WashingColumn2 .Cooler.Total_Plant_Cost': 0.0014174597665748557, 'WashingColumn1.SolventPump.Total_Plant_Cost': 0.0006616564886166539, 'WashingColumn2 .SolventPump.Total_Plant_Cost': 0.000349229217851776, 'Condenser1.Pump.Total_Plant_Cost': 0.0013622339471519344, 'Condenser2 .Pump.Total_Plant_Cost': 0.0007190013308713036, 'Stripper1.RefluxDrum.Total_Plant_Cost': 0.0017903646162568281, 'Stripper2.RefluxDrum.Total_Plant_Cost': 0.0032663203316724934, 'LeanSolventPump1.Total_Plant_Cost': 0, 'LeanSolventPump2.Total_Plant_Cost': 0, 'SolventStorageTank1.Total_Plant_Cost': 0.013310971712170331, 'SolventStorageTank2.Total_Plant_Cost': 0.007025670147371023, 'WashingSolventTank1.Total_Plant_Cost': 0.0017903646162568281, 'WashingSolventTank2.Total_Plant_Cost': 0.0009449731777165704, 'SolventStripperReclaimer1.Total_Plant_Cost': 0.007044695555271432, 'SolventStripperReclaimer2.Total_Plant_Cost': 0.0037182640253630274, 'SolventReclaimerCooler1.Total_Plant_Cost': 0.007005774585352805, 'SolventReclaimerCooler2.Total_Plant_Cost': 0.0036977211301952757, 'SolventFiltration1.Total_Plant_Cost': 0.03370555994953072, 'SolventFiltration2.Total_Plant_Cost': 0.017790147215272827, 'TPC': 3.8975757737963006, 'Utilities.Water': 0.08656566413033356, 'Utilities.Steam': 0.05654235740578879, 'Utilities.Solvent': 0.16280820375746133, 'Utilities.Electricity': 0.038248804836724035, 'TotalCost.Capital': 0.1296586669958502, 'TotalCost.Fixed': 3.2882849999999997, 'TotalCost.Variable': 0.3441650301303077, 'TotalCost.PerElectricity': 71.63979975508192, 'TotalCost.PerCapture': 734.4190131575258}}, 'graphError': 19, 'nodeError': {'CCSI_MEAModel': -1, 'CCS_costing': -1}, 'nodeSettings': {'CCSI_MEAModel': {'Visible': False, 'Initialize Model': False, 'Reset': False, 'Reset on Fail': True, 'Retry': False, 'Allow Simulation Warnings': True, 'Max consumer reuse': 90, 'Maximum Wait Time (s)': 1440, 'Maximum Run Time (s)': 840, 'Min Status Check Interval': 4, 'Max Status Check Interval': 5, 'Override Turbine Configuration': 'NULL'}, 'CCS_costing': {}}, 'turbineMessages': {'CCSI_MEAModel': 'NULL', 'CCS_costing': 'NULL'}, 'input_vectorvals': {}, 'output_vectorvals': {'CCSI_MEAModel': {}, 'CCS_costing': {}, 'LowConc': {}}, 'session': 'e899fc3c-f98e-4749-916e-69bc00ed365a', 'Id': '32792c39-0d2b-41af-acda-461fffbd361b', 'resub': 0}
```

**Comment by boverhof** [comment]
# FOQUS Plugin Lookup 
```python
$ sed -n '345,355p' foqus_lib/framework/session/session.py 
        self.pymodels = pluginSearch.plugins(
            idString="#\s?FOQUS_PYMODEL_PLUGIN",
            pathList=[
                os.path.join(os.getcwd(), "user_plugins"),
                os.path.dirname(pymodel.__file__),
            ],
        )
        try:
            self.flowsheet.pymodels = self.pymodels
        except:
            pass
```
