### ISSUE TITLE
Extend static check suite for CI

### ISSUE THREAD

**Issue by lbianchi-lbl** [CCSI-Toolset/FOQUS#1162]
- [x] Enable import-related Pylint checks
  - [x] `wildcard-import`: Flags uses of `import *` (of which FOQUS has _a lot_) (#1252)
  - [x] `unused-import` (#1251)
  - [x] `wrong-import-order` (#1170)
    - Can use `isort` to automate (most of) the fixes
    - Similar to Black in this regard as it has both a `check` mode and an `apply` mode
- [x] Spellchecker to detect typos (See PR #1168)
- [ ] Preliminary support for type checking

**Comment by ksbeattie** [comment]
Some `isort` info:

If we add `isort` to the CI as a check here is how it should be run:

    isort --profile black --check .

To run it manually (which should happen in it's own PR before the above check is added):

    isort --profile black --check --diff .

to see details of what it would change.

And:

    isort --profile black .

to make the changes in your working dir.
