### ISSUE TITLE
FOQUS Cloud Developer Onboarding Step1

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/FOQUS#990]
# Description
Start by creating a FOQUS development environment on AWS/EC2.

# Pretasks
- [ ]  Add as developer on GITHUB CCSI-Toolset group
- [x]  Add IAM Credentials on AWS

# Subtasks
Document and take screenshots of progress, and append to this issue in comments.

## AWS EC2 VM/AMI
- [x]  Login to AWS Console
- [x]  Create AWS Windows 2016 VM 
- [x]  Login with Windows Remote Desktop from Work Laptop Computer
- [x]  install Aspen v10 ACM/AspenPlus
- [x]  Configure SLM License server
- [x]  Download then Open Example/Tutorial BFB simulation (Double Click acm Model Opens in Aspen )
- [x]  From AWS/EC2 console, Create AMI:   Tags {  "Name":"Aspen10TestImage", "Version":"1.0.0", "AspenTech":"10.1" }
- [ ] Destroy VM
### Part 1
- [ ]  Using AMI, create new VM
- [ ]  Download newest Anaconda for Windows 64 bit
- [ ]  Follow FOQUS directions for setting up developer environment, checkout FOQUS with GIT
- [ ]  Open up FOQUS UI, Run BFB example Flowsheet 
- [ ]  Confirm that flowsheet ran successfully and find the output variables
### Part 2
- [ ] FOQUS UI change configuration to use FOQUS Cloud
- [ ] Check `FOQUS UI Cloud Monitor` to view status of the cloud resources
- [ ]  Open up FOQUS UI, Run BFB example Flowsheet 
- [ ]  Using AWS Console check to see cloud resources are coming on line
- [ ]  Check EC2 Autoscaling and confirm metrics are updated correctly
- [ ]  Check EC2 instances are coming on line
- [ ]  Flowsheet job should be picked up and executed successfully 
- [ ]  Notate the IAM Role/Permissions that these EC2 instances are configured with for next set of subtasks

## FOQUS AMI
- [ ]  Using AMI, create new VM with above IAM Role/Permissions 
- [ ]  Download newest Anaconda for Windows 64 bit
- [ ]  Follow FOQUS directions for setting up developer environment, checkout FOQUS with GIT
- [ ]  Install FOQUS Windows Service and Configure for integration with existing development FOQUS Cloud

###  Notes on Configure for integration with existing development FOQUS Cloud
- The Windows Service must be configured to the correct SQS Queue, SNS Topics, S3 Buckets, and DynamoDB database.  
- Currently this is done via UserData, which is a JSON blob put in the AutoScaling/LaunchConfiguration.
- Thus a single AMI can be used for multiple deployments or even support a multi-tenant environment.
 
### Other
May use Cloud-Init in future to create a self-updating AMI that we can tie to a GIT branch
Also should run the Seal-VM script before shutting down and creating a AMI, probably needs to be upated.
- https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html
- https://github.com/CCSI-Toolset/FOQUS/blob/master/cloud/aws/Seal-VM.ps1

**Comment by boverhof** [comment]
# SLM Configuration @dghoshal-lbl 
- Add host `dudley.lbl.gov` 
- Add IP Address to SLM Server firewall with following directions: https://gitlab.com/lbnl-dst-admin/turbine-admin-tools

**Comment by boverhof** [comment]
# Demo of using BFB on AWS Cloud
https://github.com/CCSI-Toolset/FOQUS/issues/982

**Comment by dghoshal-lbl** [comment]
## Step-0: Create AWS EC2 VM/AMI and install AspenPlus

### Create AWS Windows 2016 VM

- Go to EC2>AMI Catalog. Type in Microsoft Windows 2016 in the search box.
- Select Microsoft Windows Server 2016 with SQL Server 2016 Standard because SQL Server is a required dependency for Aspen installation.You can also download and install SQL Server later.
- Select Instance Type, edit configurations and launch instance. _NOTE: Aspen installation requires at least 10 GB of free space in the primary drive. The default 30 GB for free tier will not work, as over 20 GB of space is used by the OS._
- During instance configuration, make sure you allow incoming RDP connections, by configuring the Inbound rules under Security. You can select source as "My IP" that will automatically populate the IP address of your laptop/desktop from where you will connect to the instance.
- You will also be asked to create/use a keypair to be used for your instance. Save the key as .pem file ins secure location in your computer.
- You can also generate and associate an elastic IP to the instance so that the IP does not change every time you restart it. This will be useful when configuring the license server for Aspen from within the instance.

<img width="1065" alt="P0T2S1_selectWindows2016VM" src="https://user-images.githubusercontent.com/12552293/149173944-71c964fa-d6a8-4fce-a7ef-96c26aa2810c.png">

<img width="1410" alt="P0T2S3_launchInstance" src="https://user-images.githubusercontent.com/12552293/149175180-df763cff-8fb2-4a04-9fae-3c72e6708f49.png">

### Login with Windows Remote Desktop from Work Laptop Computer

- Select the instance EC2>Instances.
- Once the instance is in 'running' state, click on Connect on top right corner.
- Generate the password using the keypair saved earlier. You will need to use this password to login to your instance using Remote Desktop.

<img width="804" alt="Screen Shot 2022-01-12 at 5 03 00 PM" src="https://user-images.githubusercontent.com/12552293/149230495-21cf7880-59c3-4d50-9f5e-e8be510d1f86.png">

- Download the remote desktop file.
- Double click the downloaded file and provide the username/password to login.

<img width="554" alt="Screen Shot 2022-01-12 at 5 04 45 PM" src="https://user-images.githubusercontent.com/12552293/149230549-925d5dae-e73b-470c-820a-ad92faa074f4.png">

### Install Aspen v10 ACM/AspenPlus

- Download the Aspen installer. You can either download it from:

1. S3 bucket on AWS (foqus2-cloud-files), or
2. EBS volume that contains the installers under Elastic Block Store>Volumes (Installers-DG). Note: _You have to only mount the volume and **not format** it._

<img width="1065" alt="Screen Shot 2022-01-12 at 10 29 36 AM" src="https://user-images.githubusercontent.com/12552293/149184274-8d568423-0d39-4c66-98d9-8c0d3058b4d4.png">

- Extract the AspenPlus installer from Aspen-V12-ENG.zip. 
- Click on Setup -> Install Now -> Install aspenOne products. 
- Install all dependencies as needed. Microsoft SQL Server and Java 8 are required for installation.

<img width="809" alt="Screen Shot 2022-01-12 at 5 19 57 PM" src="https://user-images.githubusercontent.com/12552293/149232262-a5aa75cd-739f-43ee-9829-f0d46802e5da.png">

#### Configure SLM License server

- You will have to configure the SLM license server to successfully install and use AspenPlus.
- Please refer to [this](https://github.com/CCSI-Toolset/FOQUS/issues/990#issuecomment-1010228565) to configure it.
NOTE: If you do not assign an elastic IP to your instance you may have to do this step every time to restart your instance.

### Test Aspen Installation using BFB Simulation Model

- Download the BFB simulation [acmf file](https://github.com/CCSI-Toolset/FOQUS/tree/master/examples/test_files/OUU_Remote_Turbine_BFB/BFB_v11_FBS_01_26_2018.acmf). 
- Double-click the downloaded BFB_v11_FBS_01_26_2018.acmf file. It should open in Aspen Custom Modeler. Your Aspen installation is successful.

<img width="1195" alt="Screen Shot 2022-01-12 at 10 15 24 AM" src="https://user-images.githubusercontent.com/12552293/149184439-7b5fea41-924b-44e1-a9de-1a4fd4d07f0b.png">

### Create AMI from the Instance

- To create the AMI, select the instance from EC2>Instances.
- Right-click on the instance and select Image and Templates>create image.
- Add tags as required, and create AMI.

<img width="1134" alt="Screen Shot 2022-01-12 at 10 27 30 AM" src="https://user-images.githubusercontent.com/12552293/149184399-613f2827-88c9-462a-9d84-ccd0a80932fd.png">
